export const homeObjOne = {
    id: 'about', 
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    darkText: true,
    topLine: 'Premium Bank',
    headLine: 'Transições ilimitadas com zero risco.',
    description: 'Tenha Acesso Exclusivo: Sua chave para um mundo de oportunidades sem igual, onde um potencial ilimitado aguarda atrás de cada porta.',
    buttonLabel: 'Vamos começar',
    imgStart: false,
    img: require('../../images/svg-10.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
}
export const homeObjTwo = {
    id: 'discover', 
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    darkText: false,
    topLine: 'Acesso Ilimitado',
    headLine: 'Acesso Ilimitado: Explore Sem Limites e Sem Barreiras!',
    description: 'Ter acesso ilimitado oferece a liberdade de explorar todas as vantagens e recursos sem restrições, garantindo uma experiência completa e flexível.',
    buttonLabel: 'Saiba Mais',
    imgStart: false,
    img: require('../../images/svg-2.svg').default,
    alt: 'PorcoBank',
    dark: false,
    primary: false,
}
export const homeObjThree = {
    id: 'signup', 
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    darkText: false,
    topLine: 'Junte-se a nossa equipe',
    headLine: 'Junte-se a Nós: Transforme sua Vida Financeira!',
    description: 'Junte-se a nós e faça parte de uma comunidade dedicada a alcançar o sucesso financeiro. Descubra as vantagens exclusivas de fazer parte da nossa plataforma e comece a trilhar seu caminho rumo à prosperidade hoje mesmo!',
    buttonLabel: 'Vamos começar!',
    imgStart: false,
    img: require('../../images/svg-3.svg').default,
    alt: 'Car',
    dark: false,
    primary: false,
}
export const homeObjFour = {
    id: 'about', 
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    darkText: true,
    topLine: 'Premium Bank',
    headLine: 'Transições ilimitadas com zero risco.',
    description: 'Tenha Acesso Exclusivo: Sua chave para um mundo de oportunidades sem igual, onde um potencial ilimitado aguarda atrás de cada porta.',
    buttonLabel: 'Vamos começar',
    imgStart: false,
    img: require('../../images/svg-4.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
}
export const homeObjFive = {
    id: 'discover', 
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    darkText: false,
    topLine: 'Acesso Ilimitado',
    headLine: 'Acesso Ilimitado: Explore Sem Limites e Sem Barreiras!',
    description: 'Ter acesso ilimitado oferece a liberdade de explorar todas as vantagens e recursos sem restrições, garantindo uma experiência completa e flexível.',
    buttonLabel: 'Saiba Mais',
    imgStart: false,
    img: require('../../images/svg-5.svg').default,
    alt: 'PorcoBank',
    dark: false,
    primary: false,
}
export const homeObjSix = {
    id: 'signup', 
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    darkText: true,
    topLine: 'Junte-se a nossa Equipe',
    headLine: 'Junte-se a Nós: Transforme sua Vida Financeira!',
    description: 'Junte-se a nós e faça parte de uma comunidade dedicada a alcançar o sucesso financeiro. Descubra as vantagens exclusivas de fazer parte da nossa plataforma e comece a trilhar seu caminho rumo à prosperidade hoje mesmo!',
    buttonLabel: 'Vamos começar!',
    imgStart: false,
    img: require('../../images/svg-6.svg').default,
    alt: 'Cartão de Credito',
    dark: true,
    primary: true,
}